version: 2.1
jobs:
  build-project:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: >
            python3 -m venv venv
            mkdir -p venv/bin/activate
            source venv/bin/activate
            ls -l venv/bin/activate
            chmod +x venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
        
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
          
workflows:
  default:
    jobs:
      - build-project
