version: 2.1
jobs:
  build-project:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.devops
            chmod +x ~/.devops
            echo "created devops"
            . ~/.devops/bin/activate
            echo "Activating"
            source ~/.devops/bin/activate
            echo "Activated"
            make install
            pip install --upgrade pip &&\
                pip install -r requirements.txt
            echo "Installing hadolint"
            wget -O ~/.devops/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x ~/.devops/bin/hadolint
            echo "Installed hadolint"
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.devops
        
      - run:
          name: run lint
          command: |
            echo "Run lint"
            ~/.devops/bin/activate
            make lint
          
workflows:
  default:
    jobs:
      - build-project
