version: 2.1
jobs:
  build-project:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: >
            python3 -m venv testlint
            chmod +x testlint
            echo "created testlint"
            . testlint/bin/activate
            echo "Activated"
            make install
            echo "Installing hadolint"
            wget -O testlint/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x testlint/bin/hadolint
            echo "Installed hadolint"
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./testlint
        
      - run:
          name: run lint
          command: |
            echo "Runt lint"
            . testlint/bin/activate
            make lint
          
workflows:
  default:
    jobs:
      - build-project
